#!/bin/sh
echo "Checking if Demo is installed"
if [ -d /var/data/WinePrefix/drive_c/Games/Demo ]; then
    echo "Demo is installed"
    echo "Launching Demo"

    Launch
else
    echo "Demo is not installed"
    echo "Launching Demo installer"

    InstallerQT # Launch QT GUI Installer
fi